CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT chk_users_role
        CHECK (role IN ('PARENT', 'CHILD'))
);


CREATE TABLE parent_profiles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    full_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_parent_profiles_user_id UNIQUE (user_id),
    CONSTRAINT uk_parent_profiles_email UNIQUE (email),

    CONSTRAINT fk_parent_profiles_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);


CREATE TABLE child_profiles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    age          SMALLINT    NOT NULL,
    xp           INTEGER     NOT NULL DEFAULT 0,
    level        INTEGER     NOT NULL DEFAULT 1,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_child_profiles_user_id UNIQUE (user_id),

    CONSTRAINT chk_child_profiles_age
        CHECK (age BETWEEN 10 AND 14),

    CONSTRAINT chk_child_profiles_xp
        CHECK (xp >= 0),

    CONSTRAINT chk_child_profiles_level
        CHECK (level >= 1),

    CONSTRAINT fk_child_profiles_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);


CREATE TABLE parent_child_links
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_profile_id BIGINT NOT NULL,
    child_profile_id  BIGINT NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_parent_child_link
        UNIQUE (parent_profile_id, child_profile_id),

    CONSTRAINT fk_parent_child_links_parent
        FOREIGN KEY (parent_profile_id)
            REFERENCES parent_profiles (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_parent_child_links_child
        FOREIGN KEY (child_profile_id)
            REFERENCES child_profiles (id)
            ON DELETE CASCADE
);


CREATE INDEX idx_parent_child_links_parent
    ON parent_child_links (parent_profile_id);

CREATE INDEX idx_parent_child_links_child
    ON parent_child_links (child_profile_id);