CREATE TABLE wallets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         child_profile_id BIGINT NOT NULL UNIQUE,

                         balance NUMERIC(19, 2) NOT NULL DEFAULT 1000.00,

                         currency VARCHAR(3) NOT NULL DEFAULT 'AZN',

                         created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_wallets_child
                             FOREIGN KEY (child_profile_id)
                                 REFERENCES child_profiles(id)
                                 ON DELETE CASCADE,

                         CONSTRAINT chk_wallets_balance
                             CHECK (balance >= 0),

                         CONSTRAINT chk_wallets_currency
                             CHECK (currency = 'AZN')
);