CREATE TABLE wallet_transactions (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     wallet_id BIGINT NOT NULL,

                                     type VARCHAR(20) NOT NULL,

                                     amount NUMERIC(19, 2) NOT NULL,

                                     balance_after NUMERIC(19, 2) NOT NULL,

                                     description VARCHAR(255) NOT NULL,

                                     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_wallet_transactions_wallet
                                         FOREIGN KEY (wallet_id)
                                             REFERENCES wallets(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT chk_wallet_transactions_type
                                         CHECK (type IN ('INITIAL_CREDIT', 'CREDIT', 'DEBIT')),

                                     CONSTRAINT chk_wallet_transactions_amount
                                         CHECK (amount > 0),

                                     CONSTRAINT chk_wallet_transactions_balance_after
                                         CHECK (balance_after >= 0)
);

CREATE INDEX idx_wallet_transactions_wallet_created
    ON wallet_transactions (wallet_id, created_at DESC, id DESC);

-- V4-dən əvvəl yaradılmış wallet-lərin başlanğıc tarixçəsi.
INSERT INTO wallet_transactions (
    wallet_id,
    type,
    amount,
    balance_after,
    description,
    created_at
)
SELECT
    w.id,
    'INITIAL_CREDIT',
    w.balance,
    w.balance,
    'Initial wallet balance',
    w.created_at
FROM wallets w
WHERE w.balance > 0
  AND NOT EXISTS (
    SELECT 1
    FROM wallet_transactions wt
    WHERE wt.wallet_id = w.id
);