CREATE TABLE simulation_decisions (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                      child_profile_id BIGINT NOT NULL,

                                      scenario_code VARCHAR(50) NOT NULL,

                                      option_code VARCHAR(50) NOT NULL,

                                      amount_spent NUMERIC(19, 2) NOT NULL DEFAULT 0.00,

                                      wallet_transaction_id BIGINT UNIQUE,

                                      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                      CONSTRAINT fk_simulation_decisions_child
                                          FOREIGN KEY (child_profile_id)
                                              REFERENCES child_profiles(id)
                                              ON DELETE CASCADE,

                                      CONSTRAINT fk_simulation_decisions_wallet_transaction
                                          FOREIGN KEY (wallet_transaction_id)
                                              REFERENCES wallet_transactions(id)
                                              ON DELETE SET NULL,

                                      CONSTRAINT uk_simulation_decisions_child_scenario
                                          UNIQUE (child_profile_id, scenario_code),

                                      CONSTRAINT chk_simulation_decisions_amount_spent
                                          CHECK (amount_spent >= 0)
);