spring:
  application:
    name: kids-finance-api

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/kids_finance
    username: kids_finance
    password: kids_finance_dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8081